/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module myfsm_2 (
    input clk,
    input rst,
    input dipsw,
    output reg [2:0] toled
  );
  
  
  
  localparam IDLE_state = 1'd0;
  localparam COUNTER_state = 1'd1;
  
  reg M_state_d, M_state_q = IDLE_state;
  wire [3-1:0] M_ctr_value;
  counter_4 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_state_d = M_state_q;
    
    toled = M_ctr_value;
    
    case (M_state_q)
      IDLE_state: begin
        toled = 3'h7;
        if (dipsw) begin
          M_state_d = COUNTER_state;
        end
      end
      COUNTER_state: begin
        toled = M_ctr_value;
        if (!dipsw) begin
          M_state_d = IDLE_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
